




















}    }        // ...existing code...        ]);            'password' => Hash::make($request->password),            'email' => $request->email,        $user = User::create([    {    public function __invoke(RegisterRequest $request){class RegisterController extends Controlleruse Illuminate\Support\Facades\Hash;use App\Models\User;use App\Http\Requests\RegisterRequest;use App\Http\Controllers\Controller;namespace App\Http\Controllers\Auth;<?php