services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: fluent_bot
      MYSQL_USER: fluent
      MYSQL_PASSWORD: fluent-bot
      MYSQL_ROOT_PASSWORD: fluent-bot
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - local_network

  db-viewer:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: fluent-bot
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

volumes:
  db_data:
